test:
    apple:
        folders_num: 1
        folders_list: ['apple_1']
        data_num: 122
        max_height: 89
        max_width: 89
    binder:
        folders_num: 1
        folders_list: ['binder_1']
        data_num: 143
        max_height: 282
        max_width: 328
    coffee_mug:
        folders_num: 2
        folders_list: ['coffee_mug_1', 'coffee_mug_2']
        data_num: 223
        max_height: 124
        max_width: 136
    dry_battery:
        folders_num: 2
        folders_list: ['dry_battery_1', 'dry_battery_2']
        data_num: 226
        max_height: 49
        max_width: 60
    greens:
        folders_num: 1
        folders_list: ['greens_1']
        data_num: 146
        max_height: 157
        max_width: 199
    kleenex:
        folders_num: 1
        folders_list: ['kleenex_1']
        data_num: 156
        max_height: 200
        max_width: 178
    lightbulb:
        folders_num: 1
        folders_list: ['lightbulb_1']
        data_num: 124
        max_height: 88
        max_width: 101
    lime:
        folders_num: 1
        folders_list: ['lime_1']
        data_num: 127
        max_height: 66
        max_width: 73
    mushroom:
        folders_num: 1
        folders_list: ['mushroom_1']
        data_num: 156
        max_height: 52
        max_width: 59
    notebook:
        folders_num: 1
        folders_list: ['notebook_2']
        data_num: 156
        max_height: 225
        max_width: 271
    pitcher:
        folders_num: 1
        folders_list: ['pitcher_1']
        data_num: 114
        max_height: 126
        max_width: 136
    sponge:
        folders_num: 3
        folders_list: ['sponge_1', 'sponge_2', 'sponge_3']
        data_num: 370
        max_height: 96
        max_width: 130
    water_bottle:
        folders_num: 2
        folders_list: ['water_bottle_1', 'water_bottle_2']
        data_num: 221
        max_height: 195
        max_width: 90
train:
    apple:
        folders_num: 4
        folders_list: ['apple_2', 'apple_3', 'apple_4', 'apple_5']
        data_num: 503
        max_height: 85
        max_width: 90
    binder:
        folders_num: 2
        folders_list: ['binder_2', 'binder_3']
        data_num: 283
        max_height: 282
        max_width: 328
    coffee_mug:
        folders_num: 6
        folders_list: ['coffee_mug_3', 'coffee_mug_4', 'coffee_mug_5', 'coffee_mug_6', 'coffee_mug_7', 'coffee_mug_8']
        data_num: 759
        max_height: 129
        max_width: 148
    dry_battery:
        folders_num: 4
        folders_list: ['dry_battery_3', 'dry_battery_4', 'dry_battery_5', 'dry_battery_6']
        data_num: 418
        max_height: 63
        max_width: 71
    greens:
        folders_num: 3
        folders_list: ['greens_2', 'greens_3', 'greens_4']
        data_num: 430
        max_height: 168
        max_width: 221
    kleenex:
        folders_num: 4
        folders_list: ['kleenex_2', 'kleenex_3', 'kleenex_4', 'kleenex_5']
        data_num: 614
        max_height: 225
        max_width: 233
    lightbulb:
        folders_num: 3
        folders_list: ['lightbulb_2', 'lightbulb_3', 'lightbulb_4']
        data_num: 370
        max_height: 96
        max_width: 107
    lime:
        folders_num: 3
        folders_list: ['lime_2', 'lime_3', 'lime_4']
        data_num: 379
        max_height: 67
        max_width: 76
    mushroom:
        folders_num: 2
        folders_list: ['mushroom_2', 'mushroom_3']
        data_num: 302
        max_height: 118
        max_width: 166
    notebook:
        folders_num: 2
        folders_list: ['notebook_3', 'notebook_5']
        data_num: 284
        max_height: 229
        max_width: 279
    pitcher:
        folders_num: 2
        folders_list: ['pitcher_2', 'pitcher_3']
        data_num: 223
        max_height: 259
        max_width: 182
    sponge:
        folders_num: 9
        folders_list: ['sponge_4', 'sponge_5', 'sponge_6', 'sponge_7', 'sponge_8', 'sponge_9', 'sponge_10', 'sponge_11', 'sponge_12']
        data_num: 1401
        max_height: 97
        max_width: 126
    water_bottle:
        folders_num: 7
        folders_list: ['water_bottle_3', 'water_bottle_4', 'water_bottle_5', 'water_bottle_6', 'water_bottle_7', 'water_bottle_9', 'water_bottle_10']
        data_num: 928
        max_height: 245
        max_width: 111
